import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, MessageCircle, Sparkles, Users } from 'lucide-react';
import SectionHeading from '@/components/SectionHeading';
import SocialLinks from '@/components/SocialLinks';

export const metadata: Metadata = { title: 'Binti Circles', description: 'Binti Circles brings women together for honest menstrual-health conversation, learning and community.' };

export default function BintiCirclesPage() {
  return (
    <main className="overflow-hidden bg-brand-cream text-brand-dark">
      <section className="relative min-h-[70svh] bg-[#310516] px-5 py-16 text-white sm:px-8 lg:py-24"><div className="absolute inset-0 opacity-15 [background-image:radial-gradient(circle_at_20%_20%,#d9a520_0,transparent_32%),radial-gradient(circle_at_85%_70%,#fff_0,transparent_28%)]"/><div className="relative mx-auto flex min-h-[55svh] max-w-7xl items-end"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.26em] text-brand-gold">Binti Circles</p><h1 className="mt-5 font-serif text-5xl leading-[.95] sm:text-7xl lg:text-8xl">A place to talk, learn and feel less alone.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-brand-clay">Binti Circles is the community side of the work — honest menstrual-health conversation, shared learning and women showing up for one another.</p></div></div></section>

      <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="What the circle holds" title="Connection without performance."><p>No perfect answers. No polished stories required. Just useful conversation built around women’s everyday reality.</p></SectionHeading><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="rounded-[2rem] bg-white p-8 shadow-[0_16px_50px_rgba(77,15,40,.08)]"><Users className="h-8 w-8 text-brand-berry"/><h2 className="mt-5 font-serif text-3xl">Real conversation</h2><p className="mt-4 leading-relaxed text-brand-dark-light">Space to speak about periods, work, school and confidence without shame doing the talking.</p></article><article className="rounded-[2rem] bg-brand-cream-dark p-8"><Sparkles className="h-8 w-8 text-brand-gold-dark"/><h2 className="mt-5 font-serif text-3xl">Useful learning</h2><p className="mt-4 leading-relaxed text-brand-dark-light">Menstrual-health information shared in language people can actually use and pass on.</p></article><article className="rounded-[2rem] bg-brand-berry p-8 text-white"><MessageCircle className="h-8 w-8 text-brand-gold"/><h2 className="mt-5 font-serif text-3xl">Community action</h2><p className="mt-4 leading-relaxed text-brand-clay">Events and activations that turn a conversation into someone feeling seen, supported or better prepared.</p></article></div></div></section>

      <section className="grid bg-brand-cream-dark lg:grid-cols-2"><div className="relative min-h-[560px]"><Image src="/impact/menstrual-health-day-2026.webp" alt="Menstrual Hygiene Day 2026 event artwork" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover object-top"/></div><div className="flex items-center px-6 py-16 sm:px-12 lg:px-16"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-brand-gold-dark">A circle in action · May 2026</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-6xl">A period-friendly world starts with showing up.</h2><p className="mt-6 text-lg leading-relaxed text-brand-dark-light">At Lang’ata Women’s Prison, Mrembo joined usikueMSHY and Kenya Youth Parliament for Water for a day of conversation, care and shared humanity.</p><Link href="/binti-charity" className="mt-8 inline-flex items-center gap-2 font-bold text-brand-berry">See Binti Charity projects <ArrowRight className="h-4 w-4"/></Link></div></div></section>

      <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><article className="rounded-[2.5rem] border border-brand-clay bg-white p-8 sm:p-11"><p className="text-xs font-bold uppercase tracking-[.22em] text-brand-gold-dark">Binti Circles</p><h2 className="mt-4 font-serif text-4xl">Community and conversation.</h2><p className="mt-5 leading-relaxed text-brand-dark-light">For people who want to join the learning, attend an activation or bring an honest menstrual-health conversation into their community.</p><Link href="/contact?type=binti_circles" className="mt-7 inline-flex items-center gap-2 font-bold text-brand-berry">Ask about Binti Circles <ArrowRight className="h-4 w-4"/></Link></article><article className="rounded-[2.5rem] bg-[#26030f] p-8 text-white sm:p-11"><p className="text-xs font-bold uppercase tracking-[.22em] text-brand-gold">Binti Charity</p><h2 className="mt-4 font-serif text-4xl">Funded product supply.</h2><p className="mt-5 leading-relaxed text-brand-clay">For organisations and individuals who want Binti to prepare and deliver Mrembo supply for an agreed school or community.</p><Link href="/binti-charity" className="mt-7 inline-flex items-center gap-2 font-bold text-brand-gold">Explore Binti Charity <ArrowRight className="h-4 w-4"/></Link></article></div></section>

      <section className="bg-brand-cream-dark px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Follow the circle" title="Stay close to the real work."/><div className="mt-9 max-w-3xl"><SocialLinks /></div></div></section>
    </main>
  );
}
