import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

import { SOCIAL_LINKS } from '@/content/site-content';

const explore = [['/our-story','Our Story'],['/shop','Shop Mrembo'],['/binti-charity','Binti Charity'],['/binti-charity#donate','Donate to schools'],['/binti-circles','Binti Circles']] as const;
const help = [['/contact','Contact'],['/delivery','Delivery'],['/returns','Returns'],['/data-request','Data request']] as const;
const legal = [['/privacy','Privacy'],['/terms','Terms'],['/consent','Messaging consent']] as const;

export default function Footer() {
  return <footer className="bg-brand-dark px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-[1.3fr_.7fr_.7fr_.8fr]"><div><h2 className="font-display text-xl font-bold">BINTI MARVELS</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-brand-clay-dark">The Kenyan company behind locally made Mrembo period care, Binti Charity and Binti Circles.</p><p className="mt-4 text-sm leading-relaxed text-brand-clay-dark">+254 717 345 841<br/>binticreationsllc@gmail.com</p><p className="mt-5 inline-flex rounded-full border border-brand-gold/35 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-brand-gold">Mrembo · Made in Kenya</p></div><div><h3 className="font-bold text-brand-gold">Explore</h3><ul className="mt-4 space-y-2 text-sm">{explore.map(([href,label])=><li key={href}><Link href={href} className="text-brand-clay-dark hover:text-white">{label}</Link></li>)}</ul></div><div><h3 className="font-bold text-brand-gold">Help</h3><ul className="mt-4 space-y-2 text-sm">{help.map(([href,label])=><li key={href}><Link href={href} className="text-brand-clay-dark hover:text-white">{label}</Link></li>)}</ul><h3 className="mt-7 font-bold text-brand-gold">Legal</h3><ul className="mt-4 space-y-2 text-sm">{legal.map(([href,label])=><li key={href}><Link href={href} className="text-brand-clay-dark hover:text-white">{label}</Link></li>)}</ul></div><div><h3 className="font-bold text-brand-gold">Follow the work</h3><div className="mt-4 grid gap-2">{SOCIAL_LINKS.map(item=><a key={item.href} href={item.href} target="_blank" rel="noreferrer" className="inline-flex items-center justify-between text-sm text-brand-clay-dark hover:text-white">{item.label}<ArrowUpRight className="h-3.5 w-3.5"/></a>)}</div></div></div><div className="mt-12 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-brand-clay-dark sm:flex-row"><p>© 2026 Binti Marvels Limited.</p><p>Made in Kenya, with dignity at the centre.</p></div></div></footer>;
}
